name: "Kibana data collector"
description: "Gets data from execution and loads to Elastic"
author: "Angel Alberto Márquez Vargas"
inputs:
  job:
    description: "Job for stats collecting"
  github-token:
    description: "Tocker for using the API"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
