name: "Kibana data collector"
description: "Gets data from execution and loads to Elastic"
author: "Angel Alberto Márquez Vargas"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
