name: "Elastic job log collector"
description: "Gets data from execution and loads to Elastic"
author: "Angel Alberto Márquez Vargas"
inputs:
  job:
    description: "Job for execution stats to be collected"
  github-token:
    description: "Tocken for using the API"
  elastic-user:
    description: "Elastic user"
  elastic-psw:
    description: "Elastic psw"
  elastic-host:
    description: "Elastic host"    
  elastic-port:
    description: "Elastic port"
  elastic-index:
    description: "Elastic index"    
outputs:
  result:
    description: "Result"
runs:
  using: "docker"
  image: "Dockerfile"
